name: curseforge
base: core24
adopt-info: curseforge
title: CurseForge
summary: CurseForge – The ultimate destination for mods & addons
description: |
  CurseForge is the ultimate game platform for discovering, installing,
  and managing mods, addons, and modpacks for your favourite games
  including Minecraft, World of Warcraft, The Sims 4, and many more.

  This app requires network-observe to be connected, until auto connection is
  approved run the following command after installing:
  sudo snap connect curseforge:network-observe
website: https://www.curseforge.com/
license: Proprietary
contact: https://github.com/Phqen1x/curseforge-snap/issues
issues: https://github.com/Phqen1x/curseforge-snap/issues
source-code: https://github.com/Phqen1x/curseforge-snap

grade: stable
confinement: strict

platforms:
  amd64:

layout:
  /opt/CurseForge:
    bind: $SNAP/opt/CurseForge

apps:
  curseforge:
    command: usr/bin/curseforge-launch
    desktop: usr/share/applications/CurseForge.desktop
    extensions: [gnome]
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      HOME: $SNAP_USER_COMMON
      GIO_MODULE_DIR: $SNAP/usr/lib/x86_64-linux-gnu/gio/modules
      ELECTRON_NO_UPDATER: "1"
    plugs:
      - audio-playback
      - browser-support
      - home
      - network
      - network-bind
      - network-observe
      - network-manager
      - removable-media
      - system-observe

parts:
  launcher:
    plugin: dump
    source: snap/local
    organize:
      launch: usr/bin/curseforge-launch
    stage-packages:
      - zenity
      - xclip
      - wl-clipboard
      - jq
    prime:
      - usr/bin/curseforge-launch
      - usr/bin/zenity
      - usr/bin/xclip
      - usr/bin/wl-copy
      - usr/bin/jq

  curseforge:
    plugin: dump
    source: .
    override-pull: |
      DEB_URL="https://curseforge.overwolf.com/downloads/curseforge-latest-linux.deb"
      curl -L -o /tmp/curseforge.deb "$DEB_URL"
      craftctl set version="$(dpkg-deb --showformat='${Version}' --show /tmp/curseforge.deb | cut -d'~' -f1)"
      dpkg-deb -x /tmp/curseforge.deb "$CRAFT_PART_SRC"
    build-packages:
      - curl
    stage-packages:
      - libasound2t64
      - libnm0
      - libnotify4
      - libnss3
      - libsecret-1-0
      - libuuid1
      - libxss1
      - libxtst6
    override-prime: |
      craftctl default
      mv usr/share/applications/curseforge.desktop usr/share/applications/CurseForge.desktop
      install -Dm644 usr/share/icons/hicolor/256x256/apps/curseforge.png meta/gui/icon.png
      sed -i 's|^Icon=.*|Icon=${SNAP}/meta/gui/icon.png|' usr/share/applications/CurseForge.desktop
    prime:
      - -usr/share/doc
      - -usr/share/man
      - -usr/share/lintian
